concourse-db:
  image: postgres:9.5
  environment:
    POSTGRES_DB: concourse
    POSTGRES_PASSWORD: concourse_pass
    POSTGRES_USER: concourse_user
    PGDATA: /database
concourse-web:
  image: gregoryarcara/concourse-bin
  links:
    - concourse-db
  command: /root/scripts/start.sh web
  ports:
    - "8080:8080"
  environment:
    CONCOURSE_LOGIN: '${CONCOURSE_LOGIN}'
    CONCOURSE_PASSWORD: '${CONCOURSE_PASSWORD}'
    CONCOURSE_EXTERNAL_URL: '${CONCOURSE_EXTERNAL_URL}'
concourse-worker:
  image: gregoryarcara/concourse-bin
  privileged: true
  links:
    - concourse-web
    - concourse-db
  command: /root/scripts/start.sh worker
